name: Unzip and Move CoramTix Source

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  move-source:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Clean old folders
        run: rm -rf coramtix-main || true

      - name: Unzip source
        run: unzip -o coramtix-main.zip -d ./coramtix-main

      - name: Move files to repo root
        run: |
          # move everything from wings-main to repo root
          mv ./coramtix-main/wings-main/* ./
          # remove the extracted folder + zip
          rm -rf coramtix-main coramtix-main.zip

      - name: Show repo tree (first 100 lines)
        run: ls -R | head -n 100

      - name: Commit moved source
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          git commit -m "Moved CoramTix source from coramtix-main/wings-main to repo root" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
