name: Build CoramTix Binaries

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unzip source
        run: unzip coramtix-main.zip -d source

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Show folder structure
        run: |
          echo "📂 Files after unzip:"
          ls -R source | head -n 200

      - name: Build binary
        run: |
          cd source/wings-main
          # Initialize module if go.mod missing
          if [ ! -f go.mod ]; then
            echo "⚠️ go.mod not found, initializing..."
            go mod init github.com/coramtix-dev/wings
            go mod tidy
          fi

          mkdir -p build
          GOOS=linux GOARCH=${{ matrix.goarch }} go build -o build/coramtix_linux_${{ matrix.goarch }} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coramtix-${{ matrix.goarch }}
          path: source/wings-main/build/*
