name: Unzip and Commit CoramTix Source

on:
  workflow_dispatch:   # run manually from Actions tab
  push:
    branches:
      - main

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Remove old extracted folder (if exists)
        run: rm -rf coramtix-main

      - name: Unzip source
        run: unzip coramtix-main.zip -d ./coramtix-main

      - name: Show extracted files
        run: |
          echo "📂 Extracted project structure:"
          ls -R ./coramtix-main | head -n 200

      - name: Commit unzipped source
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add coramtix-main
          git commit -m "Unzipped coramtix-main.zip into repository" || echo "No changes to commit"
          git push
