name: Build CoramTix Binaries

on:
  workflow_dispatch:   # run manually from Actions tab
  push:
    branches:
      - main           # also run when pushing to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unzip source
        run: unzip coramtix-main.zip -d source

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Check for go.mod
        run: |
          cd source/coramtix-main || cd source
          if [ ! -f go.mod ]; then
            echo "⚠️ go.mod not found, initializing..."
            go mod init coramtix
            go mod tidy
          fi

      - name: Build binary
        run: |
          cd source/coramtix-main || cd source
          mkdir -p build
          GOOS=linux GOARCH=${{ matrix.goarch }} go build -o build/coramtix_linux_${{ matrix.goarch }} ./wings.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coramtix-${{ matrix.goarch }}
          path: |
            source/coramtix-main/build/*
            source/build/*
