name: Build CoramTix Binaries

on:
  workflow_dispatch:   # run manually
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unzip source
        run: unzip coramtix-main.zip -d source

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Ensure Go module
        run: |
          cd source
          if [ ! -f go.mod ]; then
            echo "⚠️ go.mod not found, creating..."
            go mod init coramtix
            go mod tidy
          fi

      - name: Show folder tree (debug)
        run: |
          echo "📂 Project structure after unzip:"
          ls -R source | head -n 100

      - name: Build binary
        run: |
          cd source
          mkdir -p build
          GOOS=linux GOARCH=${{ matrix.goarch }} go build \
            -o build/coramtix_linux_${{ matrix.goarch }} ./wings.go

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coramtix-${{ matrix.goarch }}
          path: source/build/*
