name: Unzip CoramTix Source

on:
  workflow_dispatch:   # run manually
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get install -y unzip

      - name: Unzip source
        run: unzip coramtix-main.zip -d ./coramtix-main

      - name: Show extracted files
        run: |
          echo "📂 Extracted project structure:"
          ls -R ./coramtix-main | head -n 200
